### ISSUE TITLE
support no password

### ISSUE THREAD

**Issue by LukeVader-IV** [JurajNyiri/HomeAssistant-qBitTorrentAlternativeSpeed#3]
transmission can be set up without a username or password.
If the server is set up like this, this extension will not work, as it considers username and password as mandatory.

edit: i just realised it's "qBitTorrent" instead of "BitTorrent", considering qBitTorrent is a BitTorrent client, would any BitTorrent client work? if not, what would stop ano other BitTorrent application from working?

**Comment by JurajNyiri** [comment]
This integration is only for qBittorrent application. The APIs and interaction with other apps is completely different.
